version: 2
updates:
- package-ecosystem: "github-actions"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: development

- package-ecosystem: "gomod"
  directory: "/"
  schedule:
    interval: "daily"
  target-branch: development
